services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    restart: unless-stopped
    ports:
      - "8085:8080"
    volumes:
      - trainingData:/usr/share/tessdata
      - configs:/configs
    environment:
      DOCKER_ENABLE_SECURITY: "false"
      LANGS: ja_JP

volumes:
  trainingData:
  configs:
