services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    ports:
      - "8096:8096"
    volumes:
      - config:/config
      - cache:/cache
      - /Volumes/Primary/Media/Jellyfin:/media:ro  # メディアフォルダのパスを変更

volumes:
  config:
  cache:
